---

name: build

on:
  workflow_call:
    secrets:
      do-token:
        description: 'Digital Ocean access token'
        required: true
      registry:
        description: 'Digital Ocean Container Registry'
        required: true

jobs:
  build_{{ cookiecutter.backend_container_name }}:
    runs-on: ubuntu-latest
    name: Build {{ cookiecutter.backend_container_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        {% raw %}with:
          token: ${{ secrets.do-token }}{% endraw %}
      - name: Build {{ cookiecutter.backend_container_name }}
        run: |
          docker build --build-arg env=staging -t {% raw %}${{ secrets.registry }}{% endraw %}/{{ cookiecutter.backend_container_name }}:{% raw %}${{ github.sha }}{% endraw %} ./{{ cookiecutter.backend_container_name }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean Container Registry
        run: docker push {% raw %}${{ secrets.registry }}{% endraw %}/{{ cookiecutter.backend_container_name }}:{% raw %}${{ github.sha }}{% endraw %}

  build_{{ cookiecutter.nginx_container_name }}:
    runs-on: ubuntu-latest
    name: Build Nginx proxy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:{% raw %}
          token: ${{ secrets.do-token }}{% endraw %}
      - name: Build {{ cookiecutter.nginx_container_name }}
        run: |
          docker build --build-arg env=staging -t {% raw %}${{ secrets.registry }}{% endraw %}/{{ cookiecutter.nginx_container_name }}:{% raw %}${{ github.sha }}{% endraw %} ./{{ cookiecutter.nginx_container_name }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean Container Registry
        run: docker push {% raw %}${{ secrets.registry }}{% endraw %}/{{ cookiecutter.nginx_container_name }}:{% raw %}${{ github.sha }}{% endraw %}
