---

version: '3.7'

services:
  backend:
    build:
      context: ../{{ cookiecutter.backend_container_name }}
      dockerfile: ./Dockerfile
      args:
        env: "test"
    command: |
        bash -c "
        while !</dev/tcp/{{ cookiecutter.db_container_name }}-test/5432; do sleep 1; done;
        uvicorn src.main:app --workers 1 --host 0.0.0.0 --port 8000"
    environment:
      - PYTHONUNBUFFERED=0
      - PROJECT_NAME=test
      - VERSION=v2
      - DEVELOPER=nickatnight
      - ENV=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_HOST={{ cookiecutter.db_container_name }}-test
    volumes:
      - /data:/data  # to access coverage.xml
    depends_on:
      - {{ cookiecutter.db_container_name }}-test

  {{ cookiecutter.db_container_name }}-test:
    image: postgres:14.1-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_HOST={{ cookiecutter.db_container_name }}-test
