"""init

Revision ID: 3577cec8a2bb
Revises:
Create Date: 2022-10-05 02:04:44.047062

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "3577cec8a2bb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meme",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submission_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("submission_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("submission_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("permalink", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meme_id"), "meme", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meme_id"), table_name="meme")
    op.drop_table("meme")
    # ### end Alembic commands ###
