services:
  # A Docker web service
  - type: web
    name: {{ cookiecutter.project_slug }}
    runtime: docker
    plan: free
    # Trigger a deploy only if the linked branch's CI checks pass
    autoDeployTrigger: checksPass
    # Web services only. The path of the service's health check endpoint for zero-downtime deploys.
    healthCheckPath: /v1/ping
    # The command to run when starting the Docker-based service.
    dockerCommand: gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    # The path to the service's Dockerfile, relative to the repo root. Typically used for services in a monorepo.
    dockerfilePath: ./{{ cookiecutter.backend_container_name }}/Dockerfile
    # The path to the service's Docker build context, relative to the repo root. Typically used for services in a monorepo.
    dockerContext: ./{{ cookiecutter.backend_container_name }}

    # Environment variables for the application
    envVars:
      - key: PORT
        value: '10000'
      # PostgreSQL service
      - key: POSTGRES_URL
        fromDatabase:
          name: {{ cookiecutter.project_slug_db }}db
          property: connectionString
{%- if cookiecutter.use_celery == "yes" %}
      - key: REDIS_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString

  - type: worker
    name: celery-worker
    runtime: docker
    plan: free
    autoDeployTrigger: checksPass
    dockerCommand: celery --app=src worker --loglevel=info --concurrency=4
    dockerfilePath: ./{{ cookiecutter.backend_container_name }}/Dockerfile
    dockerContext: ./{{ cookiecutter.backend_container_name }}

    envVars:
      - key: PORT
        value: '10000'
      - key: POSTGRES_URL
        fromDatabase:
          name: {{ cookiecutter.project_slug_db }}db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString

  - type: redis
    name: celery-redis
    plan: free # free plans will not persist data
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
{%- endif %}
databases:
  - name: {{ cookiecutter.project_slug_db }}db
    plan: free
    postgresMajorVersion: '15'
    ipAllowList: [] # Only allow internal connections
    user: app_user
