services:
  # A Docker web service
  - type: web
    name: {{ cookiecutter.project_slug }}
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry export -f requirements.txt --output requirements.txt
    startCommand: gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --host 0.0.0.0 --port $PORT
