# fly.toml app configuration file generated for cookiecutter-fastapi-backend on {% now 'utc', '%a, %d %b %Y %H:%M:%S' %}
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '{{ random_ascii_string(8) }}-{{ uuid4() }}'
primary_region = 'sjc'

[env]
  DEBUG = 'false'
  VERSION = 'v1'

[build]

[processes]
  fastapi = 'gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=60'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['fastapi']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
