name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    uses: nickatnight/gha-workflow/.github/workflows/pre-commit.yml@main

  tests:
    uses: ./.github/workflows/test.yml
